version: "3.4"

services:
  app:
    build:
      context: .
      target: app_dev
    ports:
      - 3000:5000
    volumes:
      - ./app:/usr/src/app

  server:
    build:
      context: .
    ports:
      - 8080:8081
